In [1]:
import pandas as panda




from google.colab import drive
drive.mount('/content/drive')




df = panda.read_csv('/content/drive/MyDrive/330weathermanhattenyellowtaxis.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
df.head(10)

,dropoff_datetime_hour,DOLocationID,VendorID,trip_distance,fare_amount,total_amount,extra,RatecodeID,payment_type,tip_amount,...,feels_like,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,clouds_all,weather_main,weather_description
0,2018-12-31 13:00:00,140,2.0,3.15,15.0,19.560000,0.5,1.0,1.0,3.260000,...,3.77,5.97,7.60,1026.0,70.0,5.36,177.0,100.0,Clouds,overcast clouds
1,2018-12-31 13:00:00,243,2.0,0.83,5.5,6.800000,0.5,1.0,2.0,0.000000,...,3.77,5.97,7.60,1026.0,70.0,5.36,177.0,100.0,Clouds,overcast clouds
2,2018-12-31 14:00:00,41,2.0,1.00,5.0,6.300000,0.5,1.0,2.0,0.000000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
3,2018-12-31 14:00:00,48,2.0,2.32,11.0,12.786667,0.5,1.0,1.0,0.486667,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
4,2018-12-31 14:00:00,68,2.0,1.46,7.5,11.440000,0.5,1.0,1.0,2.640000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
5,2018-12-31 14:00:00,75,2.0,0.46,3.5,4.800000,0.5,1.0,2.0,0.000000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
6,2018-12-31 14:00:00,107,2.0,1.94,8.0,11.620000,0.5,1.0,1.0,2.320000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
7,2018-12-31 14:00:00,114,2.0,3.01,12.0,15.960000,0.5,1.0,1.0,2.660000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
8,2018-12-31 14:00:00,140,2.0,3.87,13.5,15.880000,0.5,1.0,1.0,1.080000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain
9,2018-12-31 14:00:00,141,2.0,3.59,14.0,18.360000,0.5,1.0,1.0,3.060000,...,2.98,5.89,7.12,1025.0,74.0,6.71,150.0,100.0,Rain,light rain

In [3]:
df.tail(10)

,dropoff_datetime_hour,DOLocationID,VendorID,trip_distance,fare_amount,total_amount,extra,RatecodeID,payment_type,tip_amount,...,feels_like,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,clouds_all,weather_main,weather_description
554350,2019-12-31 18:00:00,237,2.0,1.389077,8.137821,14.054231,1.693590,1.0,1.0,1.647410,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554351,2019-12-31 18:00:00,238,2.0,1.837112,8.922383,14.824440,1.750903,1.0,1.0,1.884043,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554352,2019-12-31 18:00:00,239,2.0,1.646040,8.524217,14.568319,1.884615,1.0,1.0,1.796838,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554353,2019-12-31 18:00:00,243,1.0,4.870000,22.156250,28.893750,2.437500,1.0,1.0,3.971250,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554354,2019-12-31 18:00:00,244,2.0,4.034737,17.144737,23.283158,1.828947,1.0,1.0,3.061842,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554355,2019-12-31 18:00:00,246,2.0,2.042101,10.378623,16.489638,1.811594,1.0,1.0,1.847971,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554356,2019-12-31 18:00:00,249,2.0,1.677706,8.625000,14.821412,1.888235,1.0,1.0,2.001118,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554357,2019-12-31 18:00:00,261,2.0,2.904375,12.890625,18.639375,2.203125,1.0,1.0,1.531562,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554358,2019-12-31 18:00:00,262,2.0,2.114121,10.173077,16.494396,1.798352,1.0,1.0,2.001868,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds
554359,2019-12-31 18:00:00,263,2.0,1.692676,8.269366,14.149754,1.875000,1.0,1.0,1.697993,...,3.11,5.06,7.0,1005.0,72.0,4.6,240.0,75.0,Clouds,broken clouds

In [4]:
df.dtypes

dropoff_datetime_hour                       object
DOLocationID                                 int64
VendorID                                   float64
trip_distance                              float64
fare_amount                                float64
total_amount                               float64
extra                                      float64
RatecodeID                                 float64
payment_type                               float64
tip_amount                                 float64
congestion_surcharge                         int64
ride_duration                              float64
average_speed                              float64
dropoff_hour                                 int64
DOLocation_area                            float64
DOLocation_perimeter                       float64
number_taxis_DOLocationID_for_this_hour      int64
dropoff_day_of_week                          int64
dropoff_day_of_month                         int64
dropoff_month                                int64
passenger_count                            float64
dt_iso                                      object
temp                                       float64
visibility                                 float64
dew_point                                  float64
feels_like                                 float64
temp_min                                   float64
temp_max                                   float64
pressure                                   float64
humidity                                   float64
wind_speed                                 float64
wind_deg                                   float64
clouds_all                                 float64
weather_main                                object
weather_description                         object
dtype: object

In [5]:
df['dropoff_datetime_hour'] =    panda.to_datetime(df['dropoff_datetime_hour'])

In [6]:
i = df['dropoff_datetime_hour'].is_monotonic_increasing

i

True

In [7]:
y = df['dt_iso'].is_monotonic_increasing

y

True

In [8]:
df.dtypes

dropoff_datetime_hour                      datetime64[ns]
DOLocationID                                        int64
VendorID                                          float64
trip_distance                                     float64
fare_amount                                       float64
total_amount                                      float64
extra                                             float64
RatecodeID                                        float64
payment_type                                      float64
tip_amount                                        float64
congestion_surcharge                                int64
ride_duration                                     float64
average_speed                                     float64
dropoff_hour                                        int64
DOLocation_area                                   float64
DOLocation_perimeter                              float64
number_taxis_DOLocationID_for_this_hour             int64
dropoff_day_of_week                                 int64
dropoff_day_of_month                                int64
dropoff_month                                       int64
passenger_count                                   float64
dt_iso                                             object
temp                                              float64
visibility                                        float64
dew_point                                         float64
feels_like                                        float64
temp_min                                          float64
temp_max                                          float64
pressure                                          float64
humidity                                          float64
wind_speed                                        float64
wind_deg                                          float64
clouds_all                                        float64
weather_main                                       object
weather_description                                object
dtype: object

In [9]:
df =   df.drop(['dropoff_datetime_hour'], axis=1)

In [10]:
df =   df.drop(['dt_iso'], axis=1)

In [11]:
df['busyness'] =   df['number_taxis_DOLocationID_for_this_hour'] / df['DOLocation_area']

In [12]:
df =   df.drop('number_taxis_DOLocationID_for_this_hour',  axis=1)

In [13]:
import pandas as panda
import numpy as nump


df['busyness'] = df['busyness'].astype(float)



bins = nump.percentile(df['busyness'], [0, 20, 40, 60, 80, 100])


labels = [1, 2, 3, 4, 5]


df['busyness'] = panda.cut(df['busyness'], bins=bins, labels=labels, include_lowest=True)

In [14]:

yx =   ['DOLocationID',   'VendorID',    'RatecodeID',   'payment_type',
                      'dropoff_hour',   'dropoff_day_of_week',    'dropoff_day_of_month',
                                'dropoff_month', 'weather_description', 'weather_main']


df = panda.get_dummies(df, columns=yx)


print(df.head())

   trip_distance  fare_amount  total_amount  extra  tip_amount  \
0           3.15         15.0     19.560000    0.5    3.260000
1           0.83          5.5      6.800000    0.5    0.000000
2           1.00          5.0      6.300000    0.5    0.000000
3           2.32         11.0     12.786667    0.5    0.486667
4           1.46          7.5     11.440000    0.5    2.640000

   congestion_surcharge  ride_duration  average_speed  DOLocation_area  \
0                     1      21.150000       8.936170         0.000114
1                     1       5.550000       8.972973         0.000438
2                     1       3.816667      15.720524         0.000143
3                     1      13.788889       9.586343         0.000094
4                     1       7.850000      11.159236         0.000111

   DOLocation_perimeter  ...  weather_main_Clouds  weather_main_Drizzle  \
0              0.047584  ...                    1                     0
1              0.094331  ...                    1                     0
2              0.052793  ...                    0                     0
3              0.043747  ...                    0                     0
4              0.049337  ...                    0                     0

   weather_main_Fog  weather_main_Haze  weather_main_Mist  weather_main_Rain  \
0                 0                  0                  0                  0
1                 0                  0                  0                  0
2                 0                  0                  0                  1
3                 0                  0                  0                  1
4                 0                  0                  0                  1

   weather_main_Smoke  weather_main_Snow  weather_main_Squall  \
0                   0                  0                    0
1                   0                  0                    0
2                   0                  0                    0
3                   0                  0                    0
4                   0                  0                    0

   weather_main_Thunderstorm
0                          0
1                          0
2                          0
3                          0
4                          0

[5 rows x 211 columns]

In [15]:
df.to_csv('/content/drive/MyDrive/feature_complete2.2manhattenyellowtaxis.csv', index=False)